package jay.yydebug;

/** debugging interface for parsers generated by jay -t */

public interface yyDebug {

  void push (int state, Object value);
  void lex (int state, int token, String name, Object value);
  void shift (int from, int to, int errorFlag);
  void pop (int state);
  void discard (int state, int token, String name, Object value);
  void reduce (int from, int to, int rule, String text, int len);
  void shift (int from, int to);
  void accept (Object value);
  void error (String message);
  void reject ();

}
